### PR TITLE
Created a file of councils with their affliated links

### PR DESCRIPTION
**Pull request by ArchangelEkim**
List of councils and their homepage link and infocouncil link if they have one. This should make it easier to quickly create scrapers for those with infocouncil and show which ones will need further code.

### CODE REVIEW

**Comment by ArchangelEkim** [comment]
Nb: this currently only includes councils in greater metro sydney area. Thus Illawarra and Newcastle regions are not listed yet as well as other states.

**Comment by catatonicChimp** [comment]
Hey @ArchangelEkim 
Can you move that data into the existing council markdown document
https://github.com/yimbymelbourne/council-meeting-agenda-scraper/blob/main/docs/councils.md

**Comment by ArchangelEkim** [comment]
The data is different tho? I would be adding new columns to council.md for no reason. This is just a CSV file for creating infocouncil scraper classes.

**Comment by AKST** [comment]
@catatonicChimp i think based on the discussion in discord, I think the intention of this as a seperate file is provide data to be consumed by the app to configure different scrappers

**Pull request merged**
