### PR TITLE
FEAT: Manningham scraper

### LINKED ISSUE #64: [New Scraper] VIC: Manningham
**Council Name:**
Manningham Council

**Link to agenda webpage:**
https://www.manningham.vic.gov.au/about-council/how-council-works/council-meetings

**Webpage quirks**
It's odd; it uses teaser blocks in a 3-month group. Which then have to be clicked on to access files.

**Additional context**
image

### PR DESCRIPTION
**Pull request by ryanward-io**
Closes #64.

Mostly straightforward except for the webpage requests.
I was getting a 404 using the following from `base.py` as part of the `fetch_with_requests` method.
``` python
    DEFAULTHEADERS = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3",
        "Accept-Language": "en-US,en;q=0.9",
        "Referer": "https://www.google.com/",
        "Connection": "keep-alive",
        "Accept": "application/json, text/html, application/xml, text/plain",
    }
```

After some investigation it was `User-Agent` causing the issue, and removing this header key returned 200 and the expected webpage.

Because of this change, I also had to update a test which was checking `fetch_with_requests` but with no `**kwargs` param. I updated the test to match the function in `base.py`. Updating tests might be out of scope of this and it might still fail with Github Actions so keen for ideas on how to resolve.

Best case scenario is that there is a small bug in the DEFAULTHEADERS User-Agent value but I couldn't see it.

### CODE REVIEW

**Comment by ryanward-io** [comment]
Just to provide some screenshots/ code to replicate the header issue:

``` python
import requests
url = "https://www.manningham.vic.gov.au/about-council/how-council-works/council-meetings/"

# SAME AS DEFAULT_HEADERS USER-AGENT
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"}
print(requests.get(url, headers=headers))
# >> <Response [404]>

# REQUESTS DEFAULT
headers = {"User-Agent": "python-requests/2.28.0"}
print(requests.get(url, headers=headers))
# >> <Response [200]>

# REMOVING ENTIRELY
headers = {"User-Agent": None}
print(requests.get(url, headers=headers))
# >> <Response [200]>
```



image
image

**Comment by ryanward-io** [comment]
Other option is not using `fetch_with_requests` method for this and just running my own request to avoid the test. Anyway keen for thoughts.

**Comment by ArchangelEkim** [comment]
@ryanward-io I've worked out there is not a significant issue, the default headers just need to update the chrome version.

**Comment by ArchangelEkim** [comment]
Yep just need @jonobri or @chrisobi02 to approve

**Comment by ArchangelEkim** [comment]
@ryanward-io my fix has been merged, you can go ahead and redo the Manningham scraper and it should work this time.

**Pull request closed without merging**
