### PR TITLE
34 feature implement unit testing

### PR DESCRIPTION
**Pull request by ArchangelEkim**
Implement the current 2 test functions so future prs can be tested. Advise to keep this issue open until a satisfactory testing base is established.

### CODE REVIEW

**Comment by ArchangelEkim** [comment]
@chrisobi02 Found an issue with the workflow file, I'm not familiar with github workflow files yet so I am not sure where the issue is. It looks fine for me.

This is the error that is raised:

``` ModuleNotFoundError: No module named 'pip.utils' ```

**Comment by chrisobi02** [comment]
Can dig in tonight- looks like I haven't set python up properly or
something? Would be wild since the pipeline is almost out of the box

**Comment by ArchangelEkim** [comment]
Well that fixed one thing ahah! Onto the next.

**Comment by chrisobi02** [comment]
may end up needing to do a big refactor of all the files

**Comment by ArchangelEkim** [comment]
I think it will need a complete refactoring. I restructured some of the poetry toml file to install dependencies better and match the project name with the repo. However, I still get errors with flake8, which is weird because running the actions locally works for me.

**Comment by ArchangelEkim** [comment]
Yes!!! I got it running!!!

**Comment by ArchangelEkim** [comment]
Now just refactor so it does each scraper individually.

**Comment by ArchangelEkim** [comment]
Tests are running but there are errors which we should catch.

**Comment by chrisobi02** [comment]
this is excellent news, the pipeline is doing its job

**Comment by ArchangelEkim** [comment]
One big issue is when selenium is used. Chrome or chromedriver isn't installed on these virtual machines.

**Comment by jonobri** [comment]
I've definitely seen this able to be done in previous repos. I believe you have the CI/CD pipeline install some version of chromium before tests are run. This takes a little bit of time, but we have a lot of free minutes so I'm not too worried here!

**Comment by ArchangelEkim** [comment]
Oh yeah, its not a big issue. What is troubling me is whether we should start refactoring so that poetry can actually build the package each time properly or wait until all council scrapers are done.

**Comment by ArchangelEkim** [comment]
I feel refactoring now might be best, and I am thinking its best if we designed a test file for each scraper too or make it a requirement that each information extraction is separated into a function each of their own by a set standard that can be tested more precisely in parallel. This way I can also set a standard of information formatting that will make it easier later on.

**Comment by chrisobi02** [comment]
I agree 100% @ArchangelEkim, I'm currently splitting it out to make poetry work.

**Comment by chrisobi02** [comment]
@ArchangelEkim Does this refactor look good to you? Means packing up (next on the list), will be easier. @register_sraper still works, which is nice. still need to update nsw directory and write down a list of all the broken ones

**Comment by ArchangelEkim** [comment]
This is looking good, I'll have to get around to checking it out tmr maybe. I'll also do some testing but I see where you are going with this!

**Comment by chrisobi02** [comment]
yeah no rush, I just wanted to get something out tonight. I think there may be some extra pain in the tests for things like timeouts.

**Comment by ArchangelEkim** [comment]
Okay now, everything is mostly working.. One issue is that some scrapers seem to time out when run from GitHub actions. Major restructuring is mostly done from my point of view, but there may be more to do @chrisobi02. 

Next, I would like to refactor the scraper classes to implement data gathering with each scraper logic encapsulated in a function, it should take in some souped HTML and spit out the relevant data in a standard format.

**Comment by chrisobi02** [comment]
I'm going to do another once through to get rid of the __main__ functions in each file. Re changing the structure so there's more sub-functions, would that mean scraper() as is would become 2 functions that do:
1. get the council agenda page, like `get_page(agenda_ur: str) -> BeatifulSoup`
2. Find a pdf: `get_agenda_link(soup: BeautifulSoup) -> ScraperReturn`

I think we could put 1. in the base scraper? It seems most of these scrapers use a different link from the base url to get the soup - we could incorporate that and make it standard.

**Comment by chrisobi02** [comment]
I've been changing main.py as well - I think we should also try and standardize the regex stuff with this - currently theyre used sometimes and other times not. a few use time regex stuff which i think we could capture in a default list of time regexes

**Comment by jonobri** [comment]
All right, everything works now, more or less. 

There has been a bit of a refactor in how the scrapers work, but I did a bunch on merge to make sure the Fetcher doesn't have to be added manually each time. 

So it works the same. The main change for people writing scrapers is that we've gone from `self.fetch_with_requests()` to `self.fetcher.fetch_with_requests()`.

**Review by jonobri — APPROVED** [review]
An insanely large merge; let's do it. 

Docs probably need work, but there should be enough to work from here.

**Pull request merged**
